root:
  askformore: false
  autoclip: false
  autoimport: true
  autosync: true
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  nocolor: false
  noconfirm: true
  nopager: false
  notifications: false
  path: gpgcli-gitcli-fs+file:///home/frebib/.local/share/pass
  recipient_hash: {}
  safecontent: false
  usesymbols: false
mounts:
  spritsail:
    askformore: false
    autoclip: false
    autoimport: true
    autosync: true
    check_recipient_hash: false
    cliptimeout: 45
    concurrency: 1
    editrecipients: false
    nocolor: false
    noconfirm: true
    nopager: false
    notifications: false
    path: gpgcli-gitcli-fs+file:///home/frebib/.local/share/pass-spritsail
    recipient_hash: {}
    safecontent: false
    usesymbols: false
