$clean_ext = "bbl run.xml eps-converted-to.pdf";
$pdf_mode = 1;
$pdf_previewer = 'evince';
$latex = 'xetex -shell-escape';
$pdflatex = 'xelatex -shell-escape';

add_cus_dep('glo', 'gls', 0, 'run_makeglossaries');
add_cus_dep('acn', 'acr', 0, 'run_makeglossaries');
sub run_makeglossaries {
  if ( $silent ) {
    system "makeglossaries -q '$_[0]'";
  }
  else {
    system "makeglossaries '$_[0]'";
  };
}
