# source: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/alacritty-colors.toml
# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "{{ background }}"
foreground = "{{ foreground }}"

[colors.normal]
black   = "{{ color0 }}"
red     = "{{ color1 }}"
green   = "{{ color2 }}"
yellow  = "{{ color3 }}"
blue    = "{{ color4 }}"
magenta = "{{ color5 }}"
cyan    = "{{ color6 }}"
white   = "{{ color7 }}"

[colors.bright]
black   = "{{ color8 }}"
red     = "{{ color9 }}"
green   = "{{ color10 }}"
yellow  = "{{ color11 }}"
blue    = "{{ color12 }}"
magenta = "{{ color13 }}"
cyan    = "{{ color14 }}"
white   = "{{ color15 }}"
