#!/bin/sh

# Run all system xinitrc shell scripts
xinitdir="/etc/X11/xinit/xinitrc.d"
if [ -d "$xinitdir" ]; then
    for script in $xinitdir/*; do
        echo "Loading xinit script $script"
        if [ -x "$script" -a ! -d "$script" ]; then
            . "$script"
        fi
    done
fi

source $HOME/.profile

xrdb -merge $XDG_CONFIG_HOME/X11/xresources
xrandr --dpi $(xrdb -query | grep -i xft.dpi | cut -d: -f2)
xrandr --output eDP1 --primary

setxkbmap -option caps:none
xset r rate 200 18

~/.local/share/surface-scripts/pend &
~/.local/share/surface-scripts/rotationd &

exec i3
