#!/bin/sh

# Run all system xinitrc shell scripts
xinitdir="/etc/X11/xinit/xinitrc.d"
if [ -d "$xinitdir" ]; then
    for script in $xinitdir/*; do
        echo "Loading xinit script $script"
        if [ -x "$script" -a ! -d "$script" ]; then
            . "$script"
        fi
    done
fi

source ~/.profile
source $XDG_CONFIG_HOME/X11/xsession
xrdb -merge $XDG_CONFIG_HOME/X11/xresources
~/.local/share/surfacetools/rotationd --once

exec i3
