#!/bin/sh
set -e

xrandr --output DP-0.1 --primary --mode 1920x1080 --pos 0x1080 --rotate normal \
       --output DP-0.2.1 --mode 1920x1080 --pos 0x0 --rotate inverted \
       --output DP-0.2.2.1 --mode 1920x1080 --pos 1920x0 --rotate inverted \
       --output DP-0.2.2.2.1 --mode 1920x1080 --pos 1920x1080 --rotate normal

[ -e ~/.fehbg ] && ~/.fehbg
