#!/bin/sh
xrandr --output DP-1.1 --mode 1920x1080 --pos 0x285 --rotate left --output DVI-D-0 --off --output DP-1.2.1 --primary --mode 1920x1080 --pos 1080x1080 --rotate normal --output DP-1.2.2 --mode 1920x1080 --pos 3000x285 --rotate right --output HDMI-0 --mode 1920x1080 --pos 1080x0 --rotate normal --output DVI-I-1 --off --output DVI-I-0 --off --output DP-1 --off --output DP-0 --off
