#!/bin/sh
set -e

TOP_LEFT="DP-1"
TOP_RIGHT="DP-3"
BOTTOM_LEFT="DP-5"
BOTTOM_RIGHT="HDMI-0"

xrandr --output $BOTTOM_LEFT --primary --mode 1920x1080 --pos 0x1080 --rotate normal \
       --output $TOP_LEFT --mode 1920x1080 --pos 0x0 --rotate inverted \
       --output $TOP_RIGHT --mode 1920x1080 --pos 1920x0 --rotate inverted \
       --output $BOTTOM_RIGHT --mode 1920x1080 --pos 1920x1080 --rotate normal
