#!/bin/sh

./install-pacaur.sh

pacaur -S ../packages

# Update AUR completions for zsh
aurtab

xdg-user-dirs-update

curl https://d13yacurqjgara.cloudfront.net/users/13449/screenshots/1816328/attachments/332811/Lakeside_Sunrise_3840x2160.jpg > ~/pictures/lakesidesunrise.jpg

sudo ln -s /usr/bin/vim /usr/bin/vi

systemctl enable lightdm.service
systemctl enable bluetooth.service --now
systemctl enable NetworkManager.service --now
