#!/bin/sh
set -e

dest="$HOME/.local/share"
mkdir -p "$dest"
cd "$dest"

git clone https://github.com/robbyrussell/oh-my-zsh.git oh-my-zsh
cd oh-my-zsh/plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
