#!/bin/sh
set -e

# Install pkgfile for command-not-found support
sudo pacman -S pkgfile --noconfirm --needed
sudo systemctl enable --now pkgfile-update.service
sudo pkgfile --update

dest="$HOME/.local/share"
mkdir -p "$dest"
cd "$dest"

git clone https://github.com/robbyrussell/oh-my-zsh.git oh-my-zsh
cd oh-my-zsh/plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
